### ISSUE TITLE
Concern about academic integrity

### ISSUE THREAD

**Issue by GarsenJia** [SissiXXXY/CSC173ProjectCodes#1]
Is uploading CSC173 projects on Github a violation of academic integrity?

**Comment by SissiXXXY** [comment]
It is supposed to be a private repository, thanks for the reminder.

**Comment by SissiXXXY** [comment]
> Is uploading CSC173 projects on Github a violation of academic integrity?

It is supposed to be a private repository, thanks for the reminder.
